"use client";

import Image from "next/image";
import { useEffect, useRef, useState } from "react";

/**
 * Three real ShotsHQ output compositions, floating in the hero.
 *
 * Each is a 1290×2796 PNG generated by the actual production pipeline:
 *   - Brand profile (palette, typography, voice)
 *   - gpt-image-1 backdrop with that brand's art direction
 *   - Real iPhone frame composited on top
 *   - Real app screenshot inside the screen
 *   - Crisp server-rendered headline
 *
 * Generated by `scripts/generate-hero-showcase.ts`. Three different
 * style directions to show the range — tactical-dark, warm-organic,
 * editorial — applied to the same source brand (MIKI FM).
 */

type Frame = {
  src:       string;
  alt:       string;
  tilt:      number;
  yOffset:   number;
  z:         number;
  enterTilt: number;
};

const FRAMES: Frame[] = [
  { src: "/showcase/hero-1.png", alt: "Tactical-dark style — TUNE IN. radio station list",   tilt: -5, yOffset:  18, z: 20, enterTilt: -14 },
  { src: "/showcase/hero-2.png", alt: "Warm-organic style — THE CRATE. album archive",        tilt:  3, yOffset: -16, z: 30, enterTilt:   0 },
  { src: "/showcase/hero-3.png", alt: "Editorial style — DEEP CUTS. encyclopedia",            tilt: -2, yOffset:  10, z: 10, enterTilt:  14 },
];

export function PhoneShowcase({ className = "" }: { className?: string }) {
  const ref = useRef<HTMLDivElement | null>(null);
  const [revealed, setRevealed] = useState(false);

  useEffect(() => {
    if (typeof window === "undefined") return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      setRevealed(true);
      return;
    }
    const node = ref.current;
    if (!node) return;
    const obs = new IntersectionObserver(
      (entries) => {
        for (const e of entries) {
          if (e.isIntersecting) {
            setRevealed(true);
            obs.unobserve(e.target);
          }
        }
      },
      { threshold: 0.2 },
    );
    obs.observe(node);
    return () => obs.disconnect();
  }, []);

  return (
    <div
      ref={ref}
      className={`relative w-full min-h-[440px] sm:min-h-[560px] flex items-center justify-center ${className}`}
    >
      {/* Soft accent glow behind the cluster */}
      <div
        aria-hidden
        className="absolute inset-x-0 top-1/2 -translate-y-1/2 h-[80%] pointer-events-none transition-opacity duration-700 ease-[cubic-bezier(0.32,0.72,0,1)]"
        style={{
          background:
            "radial-gradient(ellipse at center, color-mix(in srgb, var(--accent) 18%, transparent) 0%, transparent 65%)",
          opacity: revealed ? 1 : 0,
        }}
      />

      <div className="relative z-10 grid grid-cols-1 sm:grid-cols-3 gap-4 sm:gap-3 lg:gap-4 items-center w-full max-w-[300px] sm:max-w-[640px]">
        {FRAMES.map((f, i) => {
          const settled = `rotate(${f.tilt}deg) translateY(${f.yOffset}px)`;
          const enter   = `rotate(${f.enterTilt}deg) translateY(${f.yOffset + 32}px)`;
          return (
            <div
              key={f.src}
              className="phone-frame-wrap group relative aspect-[9/19.5] transition-all duration-[900ms] ease-[cubic-bezier(0.32,0.72,0,1)] will-change-transform shadow-[0_24px_60px_-20px_rgba(0,0,0,0.7),0_8px_16px_-8px_rgba(0,0,0,0.5)]"
              style={{
                transform: revealed ? settled : enter,
                opacity:   revealed ? 1 : 0,
                transitionDelay: `${i * 110}ms`,
                zIndex: f.z,
              }}
            >
              <Image
                src={f.src}
                alt={f.alt}
                fill
                priority={i === 1}
                sizes="(max-width: 639px) 80vw, (max-width: 1024px) 30vw, 220px"
                className="object-cover select-none"
                draggable={false}
              />
            </div>
          );
        })}
      </div>

      <style>{`
        @media (max-width: 639px) {
          .phone-frame-wrap {
            transform: none !important;
          }
        }
      `}</style>
    </div>
  );
}
